language: node_js
node_js:
- '7'
- '6'
- '5'
- '10'
deploy:
  provider: npm
  email: ojj11@users.noreply.github.com
  api_key:
    secure: QmKE22jRA/nqqmLs0eBGQPcpQGJs3/sfY2elpKpEwkcnnA3fEdxV98a+dwP09KAHPr89Q9FpM4dg+xfVqe+AFIpr3fAvWnvqYW/ggQ8uo3hkaRXSNmVEQAFPNRPiuJ0cJ4BTRIRNur8w33u41irz9RBCyi8dRTUzOFKqewJOWzHteNhCRtHC4bG3C44e6FnHuxPjqE3QXXIf16TMbom8d2HhH//C3i9ceu3Tz710lBQyshdZU1tNcl+YznlySgJeZOI8LbWArK72RW1T/xGk/qgkC0QQcJa0AesbywIHwjol+v17LvueYiuqEV51Azer8MC1s0qCz/t8S8ogwB/8npGrDHdFoOmSC1Yk84YY+vCPR5Bnyw9OSzzRG5Az7WoTaaQ9RI+S/vpI2Goxqp1ygWhCkscHILhTq/Bxlywo3hVzvCzxgqOEBZNi4NNjWm6v/II2DTbrclraMcel3qYNh9x3aLkWDXuFmsQTVNz5tGf/LsVxp+srrOKKDMbJK/YJJpiERi4KVzhyQOiXDssWPIxj83EnUYlM06atqRaZv7tMyZcknt+iX6PIRYys4ivL1Xt+rE/2bBSGoJzqkN7QsEWthqitno9TYkdK+MVw9jzvr8MD/52x3fzwxGg6UHyt+qwfu8/LnxRlOeWcY5HNripNhHNLO2IpPkHJ+1qKGYg=
  on:
    tags: true
    repo: ojj11/analyse-control
